### ISSUE TITLE
Extend analaysis CLI `irrad_analyse`

### ISSUE THREAD

**Issue by leloup314** [cyclotron-bonn/irrad_control#2]
Since v1.3.0, the [`irrad_analyse` CLI](https://github.com/SiLab-Bonn/irrad_control/releases/tag/v1.3.0)  provides different analysis for output data of `irrad_control`. There are currently 4 different base analysis procedures:

- `--damage` for analysing the radiation damage distributions after irradiation scans (implemented)
- `--calibration` for analysing beam monitor calibrations, recorded with `irrad_control`(implemented)
-  `--scan` for analaysing the progress of a scan w.r.t. damage, beam currents, etc (TBD)
- `--beam` for analysing the pure beam parameters such as beam current over time, positions, etc (TBD)

The `--scan` as well as `--beam` need to be implemented still in analysis and plotting. For this, a new branch `extend_analysis` should be made (from `main`) in which this will be implemented

**Comment by leloup314** [comment]
Of course, to use the CLI you need to follow the steps in the [README](https://github.com/cyclotron-bonn/irrad_control#readme) and install `irrad_control` first. Also, it could be useful to install [ViTables](https://github.com/uvemas/ViTables), a software with which you can view .h5 files

**Comment by bedakno** [comment]
Better late than never: I have pushed my work so far to the `extend_analysis`-branch. In its [folder for testing purposes](https://github.com/cyclotron-bonn/irrad_control/tree/extend_analysis/tests/analysis/fixtures) there are also the .pdf files they create respectively. It would be nice if you could take a quick look into them and give short feedback about the plotted information.. does sth miss or not quite understandable etc.? The overall looks and layout (labels, axes etc) will be updated shortly. My focus was on getting the plots together rather than making them look nice in the first version as that would be unnecessary if some will be changed anyway.

**Comment by leloup314** [comment]
Looks nice so far! Some remarks

- When plotting the beam current, use the `'-'` (or sth else which is not indivudial points) linestyle to avoid plotting ~O(1e6) points ;)
- Use the matplotlib default colors `C0`, `C1`, ...`CN` for plotting different datasets in one plot
- In the scan analysis, histogram the proton fluence over all rows
- Whenever you histogram stuff, put the `mean` and `std` of the distribution in the legend
- Plot TID as well as fluence on the "damage" axis where the fluence is the primary damage quantity

**Comment by bedakno** [comment]
I implemented some of your remarks. More will follow.

**Comment by leloup314** [comment]
- Please format `mean` and `std` like (`mean ± std`) `unit` in the labels. 
- Check again the axis lables
- The main interest in terms of damage is the equivalent fluence in [neq/cm^2]. When plotting damage, put the equiv. fluence on the first and the TID on the second y axis ( TID as well as equiv. fluence are a function of the proton fluence)
- Where is the scan progression plot which had the fluence over time, beam current, etc in it?

**Comment by leloup314** [comment]
Would be cool if you could plot the beam position plots like this but not in `µm` but with percentage

![beam_pos_hist](https://user-images.githubusercontent.com/18701435/194024088-87458fba-174d-4931-bdfe-7883bf6e9531.png)

**Comment by bedakno** [comment]
I updated the --scan functionality to implement your suggestions. I am not sure about the neq-scaling in the Mrad / rows plot. I will crosscheck this.

**Comment by leloup314** [comment]
Looks like the the conversion is not yet correct. You can double check by running the damage analysis on the same file which will give you the overall fluences.
Some remarks:

- You should expect the people to view this plot have no idea what is going on so the plot as well as the title, legend, labels should be as descriptive as possible. E.g. the accumulated TID plot I don't even know what is going on with these bars and different blue/red colors. This needs to be represented better and explained by title, labels, legends etc. Use the legends and titles as well as labels to *distribute* the information about what is being shown. E.g. title="Beam current during scan", legend="Mean beam current over XY hours, XY mins:\n(X+-Y) nA". Also the beam position plot title is a little misleading. This is the relative difference of beam distribution on the left/right and upper/lower beam monitor foils. Meaning if on x axis we have +30%, that 30% more beam is on the right the on the left. You should indicate that positive x is "right", negative x is "left" and the same for y axis
- The overall plot which shows beam current, TID and Fluence show fluence in the same as beam current. This is wrong. Fluence and TID should both be steps/bars. Put the radiation damage axes e.g. TID & Fluence on the same side.
- When the x axis shows time, please put the date, e.g. 10 Aug 2022, in the label of the axis, e.g. "Time on 10 Aug 2022", and then the actual axis ticks are the hours and minutes. This saves space
- Remove redundant word like "Accumulation of TID per scan" -> "TID per scan" or ore correctly "Radiation damage per scan" because we look at TID and NEQ and maybe even primary particle fluence"
- Add a basic test for your `--scan` CLI. Just look at the [existing test](https://github.com/cyclotron-bonn/irrad_control/blob/main/tests/analysis/test_analysis.py) which test, that the CLI runs and does not crash

**Comment by leloup314** [comment]
You can test if the tests passing by calling `pytest` from the command line when you are in the package directory

**Comment by leloup314** [comment]
I have added the [`--beam`](https://github.com/cyclotron-bonn/irrad_control/blob/extend_analysis/tests/analysis/test_analysis.py#L58) and [`--scan`](https://github.com/cyclotron-bonn/irrad_control/blob/extend_analysis/tests/analysis/test_analysis.py#L65) flags to the tests, have a look. It really just uses the `os` module to call the command line and check if the corresponding subprocess returns normally. Also, I removed the PDFs from the fixtures as they can be generated by just calling the respective analysis locally.

**Comment by leloup314** [comment]
I looked at the plots again and there are still some remarks:

- BeamPosition plots: make grid, projection plots should have same height /witdh ratio, colorbar same height as actual plot, projection plots legend should be rotated according to the plot, use the `ax.text` function to place `Left/Right/Up/Down` labels **on** the axes at e.g. `ax.text(s="Left", x=-100, y=0)`, `ax.text(s="Up", x=0, y=100)` etc.
- RadiationDamageerScan plot: I still do not understand what is happening here -> What does "scans" and "alternating" mean in the legend? The fluence and TID axes are looking correctly-scaled to each other :). Can you switch the y axes? Fluence  is the primary damage and should be on the primary axis.
- ScanOverviewPlot: Rename to just  "Irradiation overview" or so. Remove the "Fluence" data, corresponding to the "Fluence / p cm^-2 s^-1, as this is not correct in the sense of the plot. Also remove the corresponding axis. Instead add the "beam loss" data which adds info. Rename the "TID" label to "Damage". The primary x axis should be the scan number, not the time

In general, try to make the legends look nice e.g if you have something longish like `"Mean beam current over n hours and m minutes\n (beam_mean +- beam_std) nA"` format it nicer with a bunch of newlines to  `"Mean beam current over time:\n\t I_beam=(beam_mean+-beam_std)nA\n\t Duration=5h 27m"`

**Comment by leloup314** [comment]
I have looked into the actual analysis code and there is a bunch of things you should change. Primarily: You will **not need numba.njit** to do the scan analysis -> This can and should be done solely by using numpys [fancy indexing](https://numpy.org/doc/stable/user/how-to-index.html) and (bool) [masking](https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html). These are a key feature of data analysis in Python and you should definitely look at them :) To give you an idea how this can work i have written some lines of code which generate a mask that selectes only beam data that was obtained while the motorstage was scanning:
    
    # Create a numpy array containing boolean False in the shape of the beam data
    mask = np.zeros_like(d[server]['Beam']['timestamp'], dtype=bool)

    # Mask where beam was scanned over area
    for idx_scan in range(d[server]['Scan'].shape[0]):
        scan_data = d[server]['Scan'][idx_scan]
        idx_row_start = np.searchsorted(d[server]['Beam']['timestamp'], scan_data['row_start_timestamp'])
        idx_row_stop = np.searchsorted(d[server]['Beam']['timestamp'], scan_data['row_stop_timestamp'])
        mask[idx_row_start:idx_row_stop] = True
    
    # This now contains only the entries where we where scanning    
    beam_currents_while_scanning = d[server]['Beam']['beam_current'][mask]

**Comment by bedakno** [comment]
The changes we talked about on Friday should be implemented now. There are some issues with the zorder on the overall plot I'll try to fix.

**Comment by leloup314** [comment]
- `--scan` analysis:
  - BeamPosition plots: make grid, projection plots should have same height /witdh ratio, colorbar same height as actual plot, projection plots legend should be rotated according to the plot, use the `ax.text` function to place `Left/Right/Up/Down` labels **on** the axes at e.g. `ax.text(s="Left", x=-100, y=0)`, `ax.text(s="Up", x=0, y=100)` etc.
  - Make "Rowwise radiation damage" plot a 2d heatmap, with row number on x axis, scan number on y axis and the bin value the Fluence / TID with nice colorbar. You can take a look on how to do this in `plotting.py`
  - "Row- and scanwise radiation damage" -> Plot `beam_loss` in same axis / plot as the rest. There is a bug in the analysis of this plot: The bars represent the damage in a row. Once some fluence has been applied in this row, it can not go to 0 again in some later scan -> Check the PDFs. Also, it would be nice to have two x axis on the bottom, one with the scan number and the another one with the respective row in that scan

**Comment by leloup314** [comment]
How is the status @bedakno ? ;)

**Comment by bedakno** [comment]
In progress. More updates to come on the weekend.

**Comment by bedakno** [comment]
> Would be cool if you could plot the beam position plots like this but not in `µm` but with percentage
> 
> ![beam_pos_hist](https://user-images.githubusercontent.com/18701435/194024088-87458fba-174d-4931-bdfe-7883bf6e9531.png)

How did you manage to generate this label/text in the 2d-hist?
